"""Sinhala-specific pronunciation rules for the voice agent."""

SINHALA_NUMBER_PRONUNCIATION_RULES = (
    "SINHALA NUMBER PRONUNCIATION RULES (use when responding in Sinhala):\n"
    "When speaking numbers in Sinhala, pronounce each digit using its Sinhala name:\n"
    "- 0 → බින්දුව (binduwa)\n"
    "- 1 → එක (eka)\n"
    "- 2 → දෙක (deka)\n"
    "- 3 → තුන (thuna)\n"
    "- 4 → හතර (hathara)\n"
    "- 5 → පහ (paha)\n"
    "- 6 → හය (haya)\n"
    "- 7 → හත (hatha)\n"
    "- 8 → අට (ata)\n"
    "- 9 → නවය (nawaya)\n"
    "- 10 → දහය (dahaya)\n\n"
    "Larger number words:\n"
    "- 20 → විස්ස (wissa)\n"
    "- 30 → තිහ (thiha)\n"
    "- 40 → හතළිහ (hathaliha)\n"
    "- 50 → පනහ (panaha)\n"
    "- 60 → හැට (haeta)\n"
    "- 70 → හැත්තෑව (haeththaewa)\n"
    "- 80 → අසූව (asūwa)\n"
    "- 90 → අනූව (anūwa)\n"
    "- 100 → සියය (siyaya)\n"
    "- 1000 → දහස (dahasa)\n"
    "- 10000 → දස දහස (dasa dahasa)\n"
    "- 100000 → ලක්ෂය (lakshaya)\n"
    "- 1000000 → දස ලක්ෂය (dasa lakshaya) / මිලියනය (miliyanaya)\n\n"
    "Rules for digit sequences (phone numbers, account numbers, OTPs, etc.):\n"
    "- Pronounce each digit individually in Sinhala with a clear pause between groups.\n"
    "- Example: 077 123 4567 → බින්දුවයි හතයි හතයි, එකයි දෙකයි තුනයි, හතරයි පහයි හයයි හත\n"
    "- Example: 011 47 00 444 → බින්දුවයි එකයි එකයි, හතරයි හතයි, බින්දුවයි බින්දුවයි, හතරයි හතරයි හතර\n\n"
    "Rules for amounts and quantities:\n"
    "- Use composed Sinhala number forms for amounts: e.g. 250 → දෙසිය පනහ (desiya panaha)\n"
    "- For currency: රුපියල් දෙසිය පනහයි සත විසි පහයි (rupiyал desiya panahai satha wisi pahai)\n\n"
)
